package dal.models;
// Generated 17 nov. 2015 23:25:28 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Accessoryavailability generated by hbm2java
 */
@Entity
@Table(name = "accessoryavailability", catalog = "ZenLounge")
public class Accessoryavailability implements java.io.Serializable {

	private AccessoryavailabilityId id;
	private int quantity;

	public Accessoryavailability() {
	}

	public Accessoryavailability(AccessoryavailabilityId id, int quantity) {
		this.id = id;
		this.quantity = quantity;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "idroom", column = @Column(name = "idroom", nullable = false) ),
			@AttributeOverride(name = "idaccessory", column = @Column(name = "idaccessory", nullable = false) ) })
	public AccessoryavailabilityId getId() {
		return this.id;
	}

	public void setId(AccessoryavailabilityId id) {
		this.id = id;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
