package dal.models;
// Generated 17 nov. 2015 23:25:28 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AccessoryavailabilityId generated by hbm2java
 */
@Embeddable
public class AccessoryavailabilityId implements java.io.Serializable {

	private int idroom;
	private int idaccessory;

	public AccessoryavailabilityId() {
	}

	public AccessoryavailabilityId(int idroom, int idaccessory) {
		this.idroom = idroom;
		this.idaccessory = idaccessory;
	}

	@Column(name = "idroom", nullable = false)
	public int getIdroom() {
		return this.idroom;
	}

	public void setIdroom(int idroom) {
		this.idroom = idroom;
	}

	@Column(name = "idaccessory", nullable = false)
	public int getIdaccessory() {
		return this.idaccessory;
	}

	public void setIdaccessory(int idaccessory) {
		this.idaccessory = idaccessory;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccessoryavailabilityId))
			return false;
		AccessoryavailabilityId castOther = (AccessoryavailabilityId) other;

		return (this.getIdroom() == castOther.getIdroom()) && (this.getIdaccessory() == castOther.getIdaccessory());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdroom();
		result = 37 * result + this.getIdaccessory();
		return result;
	}

}
