package dal.models;
// Generated 17 nov. 2015 23:25:28 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Activity generated by hbm2java
 */
@Entity
@Table(name = "activity", catalog = "ZenLounge")
public class Activity implements java.io.Serializable {

	private Integer id;
	private String name;
	private String shortdescription;
	private String longdescription;
	private Integer idactivitycategory;
	private Integer idmanager;

	public Activity() {
	}

	public Activity(String name) {
		this.name = name;
	}

	public Activity(String name, String shortdescription, String longdescription, Integer idactivitycategory,
			Integer idmanager) {
		this.name = name;
		this.shortdescription = shortdescription;
		this.longdescription = longdescription;
		this.idactivitycategory = idactivitycategory;
		this.idmanager = idmanager;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "shortdescription", length = 60)
	public String getShortdescription() {
		return this.shortdescription;
	}

	public void setShortdescription(String shortdescription) {
		this.shortdescription = shortdescription;
	}

	@Column(name = "longdescription")
	public String getLongdescription() {
		return this.longdescription;
	}

	public void setLongdescription(String longdescription) {
		this.longdescription = longdescription;
	}

	@Column(name = "idactivitycategory")
	public Integer getIdactivitycategory() {
		return this.idactivitycategory;
	}

	public void setIdactivitycategory(Integer idactivitycategory) {
		this.idactivitycategory = idactivitycategory;
	}

	@Column(name = "idmanager")
	public Integer getIdmanager() {
		return this.idmanager;
	}

	public void setIdmanager(Integer idmanager) {
		this.idmanager = idmanager;
	}

}
