package dal.models;
// Generated 17 nov. 2015 23:25:28 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "ZenLounge")
public class Category implements java.io.Serializable {

	private Integer id;
	private String name;
	private int idparentcategory;

	public Category() {
	}

	public Category(String name, int idparentcategory) {
		this.name = name;
		this.idparentcategory = idparentcategory;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "idparentcategory", nullable = false)
	public int getIdparentcategory() {
		return this.idparentcategory;
	}

	public void setIdparentcategory(int idparentcategory) {
		this.idparentcategory = idparentcategory;
	}

}
