package dal.models;
// Generated 17 nov. 2015 23:25:28 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Event generated by hbm2java
 */
@Entity
@Table(name = "event", catalog = "ZenLounge")
public class Event implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer price;
	private Integer idactivity;
	private Integer idperiod;
	private Integer idroom;
	private Integer idspeaker;

	public Event() {
	}

	public Event(String name) {
		this.name = name;
	}

	public Event(String name, Integer price, Integer idactivity, Integer idperiod, Integer idroom, Integer idspeaker) {
		this.name = name;
		this.price = price;
		this.idactivity = idactivity;
		this.idperiod = idperiod;
		this.idroom = idroom;
		this.idspeaker = idspeaker;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price")
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}

	@Column(name = "idactivity")
	public Integer getIdactivity() {
		return this.idactivity;
	}

	public void setIdactivity(Integer idactivity) {
		this.idactivity = idactivity;
	}

	@Column(name = "idperiod")
	public Integer getIdperiod() {
		return this.idperiod;
	}

	public void setIdperiod(Integer idperiod) {
		this.idperiod = idperiod;
	}

	@Column(name = "idroom")
	public Integer getIdroom() {
		return this.idroom;
	}

	public void setIdroom(Integer idroom) {
		this.idroom = idroom;
	}

	@Column(name = "idspeaker")
	public Integer getIdspeaker() {
		return this.idspeaker;
	}

	public void setIdspeaker(Integer idspeaker) {
		this.idspeaker = idspeaker;
	}

}
