package dal.models;
// Generated 17 nov. 2015 23:25:28 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Inscription generated by hbm2java
 */
@Entity
@Table(name = "inscription", catalog = "ZenLounge")
public class Inscription implements java.io.Serializable {

	private Integer id;
	private int idstate;
	private int idmember;
	private int idevent;

	public Inscription() {
	}

	public Inscription(int idstate, int idmember, int idevent) {
		this.idstate = idstate;
		this.idmember = idmember;
		this.idevent = idevent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "idstate", nullable = false)
	public int getIdstate() {
		return this.idstate;
	}

	public void setIdstate(int idstate) {
		this.idstate = idstate;
	}

	@Column(name = "idmember", nullable = false)
	public int getIdmember() {
		return this.idmember;
	}

	public void setIdmember(int idmember) {
		this.idmember = idmember;
	}

	@Column(name = "idevent", nullable = false)
	public int getIdevent() {
		return this.idevent;
	}

	public void setIdevent(int idevent) {
		this.idevent = idevent;
	}

}
