package dal.models;
// Generated 17 nov. 2015 23:25:28 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invoice generated by hbm2java
 */
@Entity
@Table(name = "invoice", catalog = "ZenLounge")
public class Invoice implements java.io.Serializable {

	private Integer id;
	private int amountpaid;
	private Date paymentdate;
	private int idpaymenttype;

	public Invoice() {
	}

	public Invoice(int amountpaid, Date paymentdate, int idpaymenttype) {
		this.amountpaid = amountpaid;
		this.paymentdate = paymentdate;
		this.idpaymenttype = idpaymenttype;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "amountpaid", nullable = false)
	public int getAmountpaid() {
		return this.amountpaid;
	}

	public void setAmountpaid(int amountpaid) {
		this.amountpaid = amountpaid;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "paymentdate", nullable = false, length = 19)
	public Date getPaymentdate() {
		return this.paymentdate;
	}

	public void setPaymentdate(Date paymentdate) {
		this.paymentdate = paymentdate;
	}

	@Column(name = "idpaymenttype", nullable = false)
	public int getIdpaymenttype() {
		return this.idpaymenttype;
	}

	public void setIdpaymenttype(int idpaymenttype) {
		this.idpaymenttype = idpaymenttype;
	}

}
