package dal.models;
// Generated 17 nov. 2015 23:25:28 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Notification generated by hbm2java
 */
@Entity
@Table(name = "notification", catalog = "ZenLounge")
public class Notification implements java.io.Serializable {

	private Integer id;
	private String label;
	private boolean isread;
	private int idcreatedby;
	private int idreceivedby;

	public Notification() {
	}

	public Notification(boolean isread, int idcreatedby, int idreceivedby) {
		this.isread = isread;
		this.idcreatedby = idcreatedby;
		this.idreceivedby = idreceivedby;
	}

	public Notification(String label, boolean isread, int idcreatedby, int idreceivedby) {
		this.label = label;
		this.isread = isread;
		this.idcreatedby = idcreatedby;
		this.idreceivedby = idreceivedby;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "label")
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "isread", nullable = false)
	public boolean isIsread() {
		return this.isread;
	}

	public void setIsread(boolean isread) {
		this.isread = isread;
	}

	@Column(name = "idcreatedby", nullable = false)
	public int getIdcreatedby() {
		return this.idcreatedby;
	}

	public void setIdcreatedby(int idcreatedby) {
		this.idcreatedby = idcreatedby;
	}

	@Column(name = "idreceivedby", nullable = false)
	public int getIdreceivedby() {
		return this.idreceivedby;
	}

	public void setIdreceivedby(int idreceivedby) {
		this.idreceivedby = idreceivedby;
	}

}
