package dal.models;
// Generated 17 nov. 2015 23:25:28 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Orders generated by hbm2java
 */
@Entity
@Table(name = "orders", catalog = "ZenLounge")
public class Orders implements java.io.Serializable {

	private Integer id;
	private boolean isvalidated;
	private Integer idinvoice;
	private int iduser;

	public Orders() {
	}

	public Orders(boolean isvalidated, int iduser) {
		this.isvalidated = isvalidated;
		this.iduser = iduser;
	}

	public Orders(boolean isvalidated, Integer idinvoice, int iduser) {
		this.isvalidated = isvalidated;
		this.idinvoice = idinvoice;
		this.iduser = iduser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "isvalidated", nullable = false)
	public boolean isIsvalidated() {
		return this.isvalidated;
	}

	public void setIsvalidated(boolean isvalidated) {
		this.isvalidated = isvalidated;
	}

	@Column(name = "idinvoice")
	public Integer getIdinvoice() {
		return this.idinvoice;
	}

	public void setIdinvoice(Integer idinvoice) {
		this.idinvoice = idinvoice;
	}

	@Column(name = "iduser", nullable = false)
	public int getIduser() {
		return this.iduser;
	}

	public void setIduser(int iduser) {
		this.iduser = iduser;
	}

}
