package dal.models;
// Generated 17 nov. 2015 23:25:28 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "ZenLounge")
public class Product implements java.io.Serializable {

	private Integer id;
	private String name;
	private float price;
	private int quantityavailable;
	private float memberreduction;
	private String urlimage;
	private int idbrand;
	private int idcategory;
	private Integer idmember;

	public Product() {
	}

	public Product(String name, float price, int quantityavailable, float memberreduction, String urlimage, int idbrand,
			int idcategory) {
		this.name = name;
		this.price = price;
		this.quantityavailable = quantityavailable;
		this.memberreduction = memberreduction;
		this.urlimage = urlimage;
		this.idbrand = idbrand;
		this.idcategory = idcategory;
	}

	public Product(String name, float price, int quantityavailable, float memberreduction, String urlimage, int idbrand,
			int idcategory, Integer idmember) {
		this.name = name;
		this.price = price;
		this.quantityavailable = quantityavailable;
		this.memberreduction = memberreduction;
		this.urlimage = urlimage;
		this.idbrand = idbrand;
		this.idcategory = idcategory;
		this.idmember = idmember;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "price", nullable = false, precision = 12, scale = 0)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@Column(name = "quantityavailable", nullable = false)
	public int getQuantityavailable() {
		return this.quantityavailable;
	}

	public void setQuantityavailable(int quantityavailable) {
		this.quantityavailable = quantityavailable;
	}

	@Column(name = "memberreduction", nullable = false, precision = 12, scale = 0)
	public float getMemberreduction() {
		return this.memberreduction;
	}

	public void setMemberreduction(float memberreduction) {
		this.memberreduction = memberreduction;
	}

	@Column(name = "urlimage", nullable = false, length = 50)
	public String getUrlimage() {
		return this.urlimage;
	}

	public void setUrlimage(String urlimage) {
		this.urlimage = urlimage;
	}

	@Column(name = "idbrand", nullable = false)
	public int getIdbrand() {
		return this.idbrand;
	}

	public void setIdbrand(int idbrand) {
		this.idbrand = idbrand;
	}

	@Column(name = "idcategory", nullable = false)
	public int getIdcategory() {
		return this.idcategory;
	}

	public void setIdcategory(int idcategory) {
		this.idcategory = idcategory;
	}

	@Column(name = "idmember")
	public Integer getIdmember() {
		return this.idmember;
	}

	public void setIdmember(Integer idmember) {
		this.idmember = idmember;
	}

}
