package dal.models;
// Generated 17 nov. 2015 23:25:28 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Recurringevent generated by hbm2java
 */
@Entity
@Table(name = "recurringevent", catalog = "ZenLounge")
public class Recurringevent implements java.io.Serializable {

	private Integer id;
	private byte nbdaysperweek;
	private byte nbweekspermonth;
	private byte nbmonthsperyear;
	private int idevent;

	public Recurringevent() {
	}

	public Recurringevent(byte nbdaysperweek, byte nbweekspermonth, byte nbmonthsperyear, int idevent) {
		this.nbdaysperweek = nbdaysperweek;
		this.nbweekspermonth = nbweekspermonth;
		this.nbmonthsperyear = nbmonthsperyear;
		this.idevent = idevent;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nbdaysperweek", nullable = false)
	public byte getNbdaysperweek() {
		return this.nbdaysperweek;
	}

	public void setNbdaysperweek(byte nbdaysperweek) {
		this.nbdaysperweek = nbdaysperweek;
	}

	@Column(name = "nbweekspermonth", nullable = false)
	public byte getNbweekspermonth() {
		return this.nbweekspermonth;
	}

	public void setNbweekspermonth(byte nbweekspermonth) {
		this.nbweekspermonth = nbweekspermonth;
	}

	@Column(name = "nbmonthsperyear", nullable = false)
	public byte getNbmonthsperyear() {
		return this.nbmonthsperyear;
	}

	public void setNbmonthsperyear(byte nbmonthsperyear) {
		this.nbmonthsperyear = nbmonthsperyear;
	}

	@Column(name = "idevent", nullable = false)
	public int getIdevent() {
		return this.idevent;
	}

	public void setIdevent(int idevent) {
		this.idevent = idevent;
	}

}
