package dal.models;
// Generated 17 nov. 2015 23:25:28 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Speaker generated by hbm2java
 */
@Entity
@Table(name = "speaker", catalog = "ZenLounge")
public class Speaker implements java.io.Serializable {

	private Integer id;
	private String job;
	private String shortdescription;
	private String detaileddescription;

	public Speaker() {
	}

	public Speaker(String job, String shortdescription, String detaileddescription) {
		this.job = job;
		this.shortdescription = shortdescription;
		this.detaileddescription = detaileddescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "job", length = 20)
	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}

	@Column(name = "shortdescription", length = 60)
	public String getShortdescription() {
		return this.shortdescription;
	}

	public void setShortdescription(String shortdescription) {
		this.shortdescription = shortdescription;
	}

	@Column(name = "detaileddescription")
	public String getDetaileddescription() {
		return this.detaileddescription;
	}

	public void setDetaileddescription(String detaileddescription) {
		this.detaileddescription = detaileddescription;
	}

}
