package dal.models;
// Generated 17 nov. 2015 23:25:28 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subscription generated by hbm2java
 */
@Entity
@Table(name = "subscription", catalog = "ZenLounge")
public class Subscription implements java.io.Serializable {

	private Integer id;
	private float anualfee;
	private Date date;

	public Subscription() {
	}

	public Subscription(float anualfee, Date date) {
		this.anualfee = anualfee;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "anualfee", nullable = false, precision = 12, scale = 0)
	public float getAnualfee() {
		return this.anualfee;
	}

	public void setAnualfee(float anualfee) {
		this.anualfee = anualfee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date", nullable = false, length = 19)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
