package dal.models;
// Generated 17 nov. 2015 23:25:28 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Subscriptionpayment generated by hbm2java
 */
@Entity
@Table(name = "subscriptionpayment", catalog = "ZenLounge")
public class Subscriptionpayment implements java.io.Serializable {

	private Integer id;
	private Date paymentdate;
	private float amountpaid;
	private int idmember;
	private Integer idpaymenttype;

	public Subscriptionpayment() {
	}

	public Subscriptionpayment(Date paymentdate, float amountpaid, int idmember) {
		this.paymentdate = paymentdate;
		this.amountpaid = amountpaid;
		this.idmember = idmember;
	}

	public Subscriptionpayment(Date paymentdate, float amountpaid, int idmember, Integer idpaymenttype) {
		this.paymentdate = paymentdate;
		this.amountpaid = amountpaid;
		this.idmember = idmember;
		this.idpaymenttype = idpaymenttype;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "paymentdate", nullable = false, length = 19)
	public Date getPaymentdate() {
		return this.paymentdate;
	}

	public void setPaymentdate(Date paymentdate) {
		this.paymentdate = paymentdate;
	}

	@Column(name = "amountpaid", nullable = false, precision = 12, scale = 0)
	public float getAmountpaid() {
		return this.amountpaid;
	}

	public void setAmountpaid(float amountpaid) {
		this.amountpaid = amountpaid;
	}

	@Column(name = "idmember", nullable = false)
	public int getIdmember() {
		return this.idmember;
	}

	public void setIdmember(int idmember) {
		this.idmember = idmember;
	}

	@Column(name = "idpaymenttype")
	public Integer getIdpaymenttype() {
		return this.idpaymenttype;
	}

	public void setIdpaymenttype(Integer idpaymenttype) {
		this.idpaymenttype = idpaymenttype;
	}

}
