package dal.models;
// Generated 17 nov. 2015 23:25:28 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "ZenLounge")
public class User implements java.io.Serializable {

	private Integer id;
	private String firstname;
	private String lastname;
	private String phonenumber;
	private String mailadress;
	private Integer idadress;
	private String login;
	private String password;
	private Integer idmember;
	private Integer idspeaker;
	private Integer idmanager;
	private Integer idadministrator;

	public User() {
	}

	public User(String firstname, String lastname, String login, String password) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.login = login;
		this.password = password;
	}

	public User(String firstname, String lastname, String phonenumber, String mailadress, Integer idadress,
			String login, String password, Integer idmember, Integer idspeaker, Integer idmanager,
			Integer idadministrator) {
		this.firstname = firstname;
		this.lastname = lastname;
		this.phonenumber = phonenumber;
		this.mailadress = mailadress;
		this.idadress = idadress;
		this.login = login;
		this.password = password;
		this.idmember = idmember;
		this.idspeaker = idspeaker;
		this.idmanager = idmanager;
		this.idadministrator = idadministrator;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "firstname", nullable = false, length = 20)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false, length = 20)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "phonenumber", length = 10)
	public String getPhonenumber() {
		return this.phonenumber;
	}

	public void setPhonenumber(String phonenumber) {
		this.phonenumber = phonenumber;
	}

	@Column(name = "mailadress", length = 50)
	public String getMailadress() {
		return this.mailadress;
	}

	public void setMailadress(String mailadress) {
		this.mailadress = mailadress;
	}

	@Column(name = "idadress")
	public Integer getIdadress() {
		return this.idadress;
	}

	public void setIdadress(Integer idadress) {
		this.idadress = idadress;
	}

	@Column(name = "login", nullable = false, length = 20)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", nullable = false, length = 64)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "idmember")
	public Integer getIdmember() {
		return this.idmember;
	}

	public void setIdmember(Integer idmember) {
		this.idmember = idmember;
	}

	@Column(name = "idspeaker")
	public Integer getIdspeaker() {
		return this.idspeaker;
	}

	public void setIdspeaker(Integer idspeaker) {
		this.idspeaker = idspeaker;
	}

	@Column(name = "idmanager")
	public Integer getIdmanager() {
		return this.idmanager;
	}

	public void setIdmanager(Integer idmanager) {
		this.idmanager = idmanager;
	}

	@Column(name = "idadministrator")
	public Integer getIdadministrator() {
		return this.idadministrator;
	}

	public void setIdadministrator(Integer idadministrator) {
		this.idadministrator = idadministrator;
	}

}
